### ISSUE TITLE
スケッチモーダルに投稿者情報を表示する

### ISSUE THREAD

**Issue by watagit** [givery-bootcamp/dena-2024-team1#171]
## 開始条件

以下のIssueが完了していること

- #130 

## 完了条件

- [ ] スケッチモーダルに投稿者情報が表示される

## 背景と概要

発表時に触ってもらうことを考慮すると、モーダル表示時に「あれ、これ投稿した人だれだ？」となりそう。
投稿した人を認識するためのUIを構築したい。

## スクリーンショット

**※投稿者情報を載せることを考慮すると、オーバーレイの色を白っぽくした方が良い**

[Figma](https://www.figma.com/design/nAkyKY6tzb5apCzYllxVfg/Web-App?node-id=225-345&t=FPfIZT8dN9VUiF1f-4)

![Image](https://github.com/givery-bootcamp/dena-2024-team1/assets/44804976/f841d9d3-3ca5-4c38-a0c0-4283fa680915)

**Comment by ayumu-1212** [comment]
バックエンドは実装済みだっちゃ
