### ISSUE TITLE
BEのアーキテクチャを考える

### ISSUE THREAD

**Issue by watagit** [givery-bootcamp/dena-2024-team1#7]
## TODO

- [x] アーキテクチャを何にするか決める
- [x] 簡単なアーキテクチャ構成図を書く
- [ ] 現状の実装をそのアーキテクチャにする

**Comment by ayumu-1212** [comment]
簡単なアーキテクチャ構成図
https://miro.com/app/board/uXjVKDes2_Y=/?moveToWidget=3458764590317524303&cot=14
