### ISSUE TITLE
OASを作成する

### ISSUE THREAD

**Issue by ayumu-1212** [givery-bootcamp/dena-2024-team1#8]

**Comment by watagit** [comment]
## 草案

- OpenAPIのスキーマファイル(.yaml)を作成する
  - ここにモデル定義やエンドポイント定義を書く
- 上記スキーマファイルを基に[OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator)を使ってGoとTypeScriptそれぞれの型を生成する
- 生成された型をフロントエンドとバックエンドそれぞれで利用する

## 参考文献

- [OpenAPI Generator と TypeScript で型安全にフロントエンド開発をしている話 - SmartHR Tech Blog](https://tech.smarthr.jp/entry/2020/08/25/135631)
- [OpenAPI からなるべく生成するフロントエンド開発](https://zenn.dev/seya/articles/070a375a5de62c)
